<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_check_all</name>
   <tag></tag>
   <elementGuidId>cbe03b1e-cfac-4c26-b3b6-51784a947d06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Check All']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#box</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>278d0c68-50ba-4197-9421-2161c91e4af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6fdb28e7-0ff2-4168-9cec-d81762371805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-10 rounded w-150 box btn bg-lambda-900 selenium_btn bg-black text-white px-10 py-5 cursor-pointer hover:bg-lambda-900</value>
      <webElementGuid>22339ee6-5f40-4e14-824e-dedc4b0f35b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>box</value>
      <webElementGuid>1510acfe-aa20-4fdd-8547-0239d64f7734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Check All</value>
      <webElementGuid>e2e80e08-dedf-4f94-bce1-25ce879ff364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;box&quot;)</value>
      <webElementGuid>a0f161a6-1182-4ff0-9ab3-801d7c00b193</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='box']</value>
      <webElementGuid>85da3531-4d44-48fb-b0c3-97478d169d6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[2]/div/div/div/div[3]/div[2]/div[2]/input</value>
      <webElementGuid>5c88a3fc-1694-4f5f-985e-756f83b9bd09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/input</value>
      <webElementGuid>4a38d7a7-76e9-4a17-aa39-49005d89b264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'box']</value>
      <webElementGuid>ddb18087-8dab-49e3-8c5c-dadc0a0f40e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
